### ISSUE TITLE
gr-igate does not send application name and version number to APRS-IS server

### ISSUE THREAD

**Issue by hessu** [pengi/gr-igate#6]
Hi,

When reviewing the patches I noticed gr-igate does not send the optional application name and version string to the APRS-IS server when logging in. As an APRS-IS server developer and operator, it'd often be very useful to get this information in the server – when trying to find out what's going on with a specific client, that info can be used to find the respective client code.

https://github.com/pengi/gr-igate/blob/master/python/aprs_is_sink.py#L56

I'd like to request it to say "user %s pass %d vers gr-igate 1.0.0-g%s" with the git commit ID in the version string for example, if possible. 1.0.0 alone will already be fine, so we can see which clients are gr-igate.

http://aprs-is.net/Connecting.aspx

Thank you!

**Comment by pengi** [comment]
I was thinking about how aprs-is servers were identifying client software. That should be a quick fix.

Thanks for the report!

**Comment by pengi** [comment]
It says "gXXXX" if it's not right on a tag. Using "git describe --dirty" to get the version number.

This one is quite hard to do auto tests for, but quite obvious when starting up the program. (I usally look at the beginning of the output every time I start it). So I keep this without auto tests for now...

Thanks for the report!

**Comment by hessu** [comment]
Excellent, thank you!
